# Generated by Django 2.2.3 on 2019-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
