# Generated by Django 2.2.3 on 2019-07-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='list_of_allergens',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restraunt_menu.AllergensModel'),
        ),
    ]
