# Generated by Django 2.2.3 on 2019-07-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt_menu', '0004_auto_20190710_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='list_of_allergens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restraunt_menu.Allergens'),
        ),
    ]
