# Generated by Django 2.2.3 on 2019-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt_menu', '0005_auto_20190710_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
