# Generated by Django 2.2.3 on 2019-07-16 09:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt_menu', '0006_auto_20190716_0919'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allergens',
            managers=[
                ('alergens', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
    ]
